Run echo "🚀 Compiling Kernel..."
🚀 Compiling Kernel...
make[1]: Entering directory '/home/runner/work/kernel-builder/kernel-builder/out'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
.config:626:warning: symbol value '' invalid for LITTLE_CPU_MASK
.config:627:warning: symbol value '' invalid for BIG_CPU_MASK
.config:628:warning: symbol value '' invalid for PRIME_CPU_MASK
*
* Restart config...
*
*
* Kernel Features
*
Page size
> 1. 4KB (ARM64_4K_PAGES)
  2. 16KB (ARM64_16K_PAGES)
  3. 64KB (ARM64_64K_PAGES)
choice[1-3?]: 1
Virtual address space size
> 1. 39-bit (ARM64_VA_BITS_39)
  2. 48-bit (ARM64_VA_BITS_48)
choice[1-2?]: 1
Build big-endian kernel (CPU_BIG_ENDIAN) [N/y/?] n
Multi-core scheduler support (SCHED_MC) [Y/n/?] y
SMT scheduler support (SCHED_SMT) [N/y/?] n
Maximum number of CPUs (2-4096) (NR_CPUS) [8] 8
Bitmask of available LITTLE CPUs (LITTLE_CPU_MASK) [] (NEW) aborted!
Console input/output is redirected. Run 'make oldconfig' to update configuration.
make[3]: *** [../scripts/kconfig/Makefile:40: silentoldconfig] Error 1
make[2]: *** [../Makefile:594: silentoldconfig] Error 2
make[1]: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/kernel.release'.  Stop.
make[1]: Leaving directory '/home/runner/work/kernel-builder/kernel-builder/out'
make: *** [Makefile:155: sub-make] Error 2
Error: Process completed with exit code 2.
